"""
Guards the committed drift artifacts against the committed bundle and against
each other.

This repo's one recurring defect is documentation citing evidence that has gone
stale or was never tracked -- the Sprint 1, Sprint 2 and Sprint 6 audits each
caught an instance (AUDIT.md §5). Sprint 8 adds three more committed artifacts
and a dashboard page that reads them, so it adds three more things that can
quietly stop describing reality: the CSVs are regenerated by a job nobody runs
on every commit, and `model_bundle/v2` can be re-exported without them.

`.github/workflows/monitoring.yml` checks the reference against the *deployed*
service. This checks it against the *repository*, which is the half CI can see
on a pull request.

Everything here reads committed files only -- no DuckDB store, no 6.36M rows --
so it runs in CI, where the raw dataset deliberately does not exist.
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from config import load_config
from features import FEATURE_COLUMNS
from monitoring.drift import (
    MIN_COMPARISON_ROWS,
    PSI_FEATURE_THRESHOLD,
    PSI_SCORE_THRESHOLD,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
PROCESSED = REPO_ROOT / "data" / "processed"
BUNDLE_META = REPO_ROOT / "model_bundle" / "v2" / "bundle_meta.json"
BUNDLE_THRESHOLD = REPO_ROOT / "model_bundle" / "v2" / "threshold.json"

# The exact columns dashboard/pages/5_Drift.py reads. Listed rather than
# inferred: the page fails in the browser and nowhere else when one goes
# missing, which is precisely the Sprint 6 dashboard regression repeating.
SCORE_COLUMNS_THE_PAGE_READS = [
    "window", "step_start", "step_end", "in_reference_period", "n_rows",
    "n_fraud", "score_psi", "score_band", "score_breached", "sufficient_sample",
    "features_breached", "n_flagged", "alerts_per_day", "capacity",
    "precision_at_capacity", "recall_at_capacity", "at_ceiling",
    "precision_at_deployed_threshold", "recall_at_deployed_threshold",
]
FEATURE_COLUMNS_THE_PAGE_READS = [
    "window", "feature", "psi", "band", "breached", "binning", "n_bins",
]


@pytest.fixture(scope="module")
def reference() -> dict:
    with open(PROCESSED / "drift_reference.json") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def score_psi() -> pd.DataFrame:
    return pd.read_csv(PROCESSED / "drift_score_psi.csv")


@pytest.fixture(scope="module")
def feature_psi() -> pd.DataFrame:
    return pd.read_csv(PROCESSED / "drift_feature_psi.csv")


# ------------------------------------------------- the reference vs the bundle


def test_the_reference_describes_the_committed_bundle(reference):
    """The stale-reference check, against the repo rather than the deployment.

    If someone re-exports the bundle and does not re-run `python tasks.py
    drift`, every PSI number on the dashboard describes a model this repo no
    longer ships.
    """
    with open(BUNDLE_META) as f:
        meta = json.load(f)
    with open(BUNDLE_THRESHOLD) as f:
        threshold = json.load(f)

    assert reference["bundle_version"] == meta["bundle_version"]
    assert reference["feature_version"] == meta["feature_version"]
    assert reference["model_name"] == meta["model_name"]
    assert reference["decision_threshold"] == threshold["decision_threshold"]


def test_the_reference_features_are_the_current_feature_set(reference):
    assert reference["features"] == FEATURE_COLUMNS


def test_the_recorded_thresholds_are_the_ones_the_detector_uses(reference):
    """The manifest is what the dashboard renders its threshold lines from, so
    it must not be able to disagree with the module that produced the numbers."""
    thresholds = reference["thresholds"]
    assert thresholds["feature_psi"] == PSI_FEATURE_THRESHOLD
    assert thresholds["score_psi"] == PSI_SCORE_THRESHOLD
    assert thresholds["min_comparison_rows"] == MIN_COMPARISON_ROWS


# ------------------------------------------------------------- artifact shape


def test_every_column_the_dashboard_reads_exists(score_psi, feature_psi):
    assert not set(SCORE_COLUMNS_THE_PAGE_READS) - set(score_psi.columns)
    assert not set(FEATURE_COLUMNS_THE_PAGE_READS) - set(feature_psi.columns)


def test_windows_are_contiguous_and_agree_across_both_files(score_psi, feature_psi):
    windows = sorted(score_psi["window"].unique())

    assert windows == list(range(len(windows))), "windows must be 0..n-1 with no gaps"
    assert sorted(feature_psi["window"].unique()) == windows
    assert len(score_psi) == len(windows), "one row per window"


def test_one_row_per_feature_per_window(feature_psi, reference):
    assert len(feature_psi) == reference["windows"]["count"] * len(FEATURE_COLUMNS)
    assert not feature_psi.duplicated(subset=["window", "feature"]).any()
    assert set(feature_psi["feature"]) == set(FEATURE_COLUMNS)


def test_window_step_ranges_are_successive_and_non_overlapping(score_psi):
    ordered = score_psi.sort_values("window")
    starts = ordered["step_start"].tolist()
    ends = ordered["step_end"].tolist()

    assert all(end >= start for start, end in zip(starts, ends, strict=True))
    assert all(nxt == prev + 1 for prev, nxt in zip(ends[:-1], starts[1:], strict=True))


# --------------------------------------------------------- internal consistency


def test_features_breached_matches_the_feature_file(score_psi, feature_psi):
    """The score file's summary count must be derivable from the long file.
    Two numbers for the same fact is how they diverge."""
    counted = feature_psi[feature_psi["breached"]].groupby("window").size()
    recorded = score_psi.set_index("window")["features_breached"]

    assert recorded.eq(counted.reindex(recorded.index, fill_value=0)).all()


def test_row_counts_agree_between_the_two_files(score_psi, feature_psi):
    per_window = feature_psi.groupby("window")["n_rows"].nunique()

    assert (per_window == 1).all(), "a window's feature rows must all report its row count"
    assert (
        feature_psi.groupby("window")["n_rows"].first()
        == score_psi.set_index("window")["n_rows"]
    ).all()


def test_a_breach_is_never_claimed_on_an_undersized_window(score_psi, feature_psi):
    """The rule that keeps PaySim's 272-row final window out of the retraining
    criteria. Reported, plotted, never a flag."""
    undersized = score_psi[score_psi["n_rows"] < MIN_COMPARISON_ROWS]

    assert not undersized["score_breached"].any()
    assert not feature_psi[feature_psi["n_rows"] < MIN_COMPARISON_ROWS]["breached"].any()


def test_breach_flags_agree_with_the_thresholds(score_psi, feature_psi):
    usable = score_psi[score_psi["sufficient_sample"]]
    assert usable["score_breached"].eq(usable["score_psi"] >= PSI_SCORE_THRESHOLD).all()

    usable_features = feature_psi[feature_psi["sufficient_sample"]]
    assert usable_features["breached"].eq(
        usable_features["psi"] >= PSI_FEATURE_THRESHOLD
    ).all()


def test_the_reference_period_flag_matches_the_recorded_cut(score_psi, reference):
    cut = reference["reference"]["step_max"]

    assert score_psi["in_reference_period"].eq(score_psi["step_end"] <= cut).all()
    # Both classes must exist, or the flag is decorative. A reference covering
    # every window would mean the comparison never leaves the training data; one
    # covering none would mean the noise-floor control was never measured.
    assert score_psi["in_reference_period"].any()
    assert not score_psi["in_reference_period"].all()


def test_the_reference_is_the_fold_config_actually_defines(reference):
    """Pins the reference to `config.yaml`, which is the half of "reference =
    the final training fold" that CI can check without the dataset.

    An audit gap: `run_drift.py` derives the cut by calling `src/cv.py`'s fold
    builder, which is right, but nothing verified that the boundaries it used are
    still the boundaries the models are trained on. Someone re-cutting the folds
    in config and not re-running the job leaves a reference describing a fold
    that no longer exists, and every number downstream silently means something
    else.
    """
    configured = load_config()["cv"]["fold_boundaries"]

    assert reference["reference"]["fold_boundaries"] == configured
    assert reference["reference"]["step_min"] < reference["reference"]["step_max"]
    assert reference["reference"]["n_fraud"] < reference["reference"]["n_rows"]


def test_capacity_is_the_configured_staffing_applied_to_the_window(score_psi):
    """`capacity` must be derivable from the CSV and config alone.

    This pins a latent coupling the audit surfaced: `window_days` in the CSV is
    the window's nominal step span, while `capacity` comes from
    `threshold.capacity_k`, which measures the span of the steps actually
    *present*. They agree on this dataset because every window has rows at both
    of its edges. If a future dataset has an empty edge hour they diverge, and
    `alerts_per_day` (nominal) would be compared against a capacity computed on
    a different notion of a day. This test fails the moment that happens.
    """
    reviews_per_day = load_config()["review_capacity"]["reviews_per_day"]
    expected = np.clip(
        np.round(reviews_per_day * score_psi["window_days"]).astype(int),
        1, score_psi["n_rows"],
    )

    assert expected.eq(score_psi["capacity"]).all()


def test_psi_is_never_negative(score_psi, feature_psi):
    """PSI is a divergence. A negative value means the shares stopped being
    shares -- most plausibly a flooring or renormalisation mistake."""
    assert (score_psi["score_psi"].dropna() >= 0).all()
    assert (feature_psi["psi"].dropna() >= 0).all()


def test_the_control_windows_are_actually_quiet(score_psi):
    """The claim MONITORING.md §3 and the dashboard both lead with: inside the
    reference period, on windows with real volume, the detector reads near zero.
    If this ever fails the noise floor has moved and every other number on the
    page needs re-reading.

    Windows 2-4 are excluded by volume, not by name: they are PaySim's early
    collapse, where a window holds ~1k rows at a ~29% fraud rate. They are
    inside the reference period and they do breach, which is the finding, not a
    defect.
    """
    control = score_psi[
        score_psi["in_reference_period"] & (score_psi["n_rows"] > 100_000)
    ]

    assert len(control) >= 10, "too few control windows to make the claim"
    assert (control["score_psi"] < PSI_SCORE_THRESHOLD).all()
