"""
Home.py

Landing page. Renders entirely from committed CSVs -- ARCHITECTURE.md §6's
cold-start rule: Streamlit Community Cloud sleeps after 12h idle (~30s
wake) and Cloud Run scales to zero (~3-5s cold start); chained, a first
API call on page load could leave a first-time visitor staring at nothing
for ~35s. No `requests` call happens anywhere in this file.

Leads with the operating question rather than with PR-AUC, deliberately.
ARCHITECTURE.md §0 is explicit that PaySim's separability makes the headline
metric a property of the dataset rather than an achievement, and that the
decision system is the deliverable. A landing page that opens with 0.9995
argues the opposite of what the project claims. The metric is still here,
one section down, with that caveat attached.
"""

import streamlit as st
from common import load_csv

st.set_page_config(page_title="AML Fraud Detection", page_icon="🔍", layout="wide")

st.title("AML Fraud Detection")
st.subheader("How many fraud analysts should a bank staff, and what does it lose if it staffs fewer?")

st.write(
    "Fraud teams cannot review every payment. They review as many as they have people for. "
    "So the useful question is not *how accurate is the model* — it is **where do you draw "
    "the line, given how many alerts a human can actually work through in a day?**"
)
st.write(
    "This project answers that with a model trained on 6.36 million mobile-money "
    "transactions, a scoring service you can send a payment to right now, and the "
    "economics that turn a review budget into a decision."
)

comparison = load_csv("model_comparison")
sweep = load_csv("capacity_sweep")
best = comparison.sort_values("capacity_precision_mean", ascending=False).iloc[0]
row_500 = sweep[sweep["reviews_per_day"] == 500].iloc[0]

st.markdown("#### If a team reviews 500 payments a day")

# Ordered deliberately: the cost of reviewing comes first, the flattering
# number last. Leading with "100% of fraud caught" would repeat, in plainer
# words, exactly the overclaim ARCHITECTURE.md §0 exists to prevent -- a
# non-technical reader hears a capability, not a property of synthetic data.
# What is actually worth knowing is that half of every analyst-hour is spent
# on a false alarm, and that number is not an artefact of PaySim.
col1, col2, col3 = st.columns(3)
col1.metric(
    "Alerts that turn out to be fraud", f"{row_500['precision']:.0%}",
    help="Of everything an analyst is asked to open, the share that is really fraud. "
         "The rest is wasted review time. Technical name: precision.",
)
col2.metric(
    "False alarms in the queue", f"{int(row_500['false_positives']):,}",
    help="Legitimate payments an analyst has to look at and clear, at this queue size.",
)
col3.metric(
    "Fraud caught, in this dataset", f"{row_500['recall']:.0%}",
    help="Of all the fraud present, the share that lands in a queue of this size. "
         "Technical name: recall. Read the caveat below before believing it.",
)

st.warning(
    "**That 100% is not a capability — it is a property of the data.** PaySim is "
    "synthetic, and its fraud is generated by near-deterministic rules (an account "
    "drained to the cent, confined to two payment types), so a model that fits it "
    "well has recovered the generator rather than solved fraud detection. No real "
    "portfolio behaves this way. The figure worth your attention is the first one: "
    "roughly half of everything an analyst opens is a false alarm, and that is what "
    "staffing actually costs.",
    icon="⚠️",
)

st.caption(
    "Change the queue size — and the cost of a review, and how much of a fraud loss is "
    "recoverable — on the **Capacity & economics** page. That trade-off, not the "
    "accuracy, is the project's actual finding."
)

st.markdown("---")

st.markdown("### Where to start")

c1, c2 = st.columns(2)
with c1:
    st.markdown(
        "**Try it yourself**\n\n"
        "**1 · Score a transaction** — load an example, press one button, and see what "
        "the live model decides and what stood out about the payment.\n\n"
        "**2 · Batch upload** — drop in a CSV, or use the bundled sample, and get a "
        "scored queue back.\n\n"
        "*Both talk to the real service. The first request of the day takes a few "
        "seconds while it wakes up.*"
    )
with c2:
    st.markdown(
        "**Read the reasoning**\n\n"
        "**3 · Capacity & economics** — the headline finding, made interactive. How many "
        "reviewers, and what is each one worth?\n\n"
        "**4 · Model card** — what the model uses, what drives it, and what it cannot do.\n\n"
        "**5 · Drift** — whether the model is still working: population shift measured "
        "over the dataset's own timeline, with the detector's noise floor measured "
        "rather than asserted."
    )

st.markdown("---")

with st.expander("So what is the deliverable, if not the model?"):
    st.markdown(
        f"For completeness: the selected model is **{best['model']}**, at a PR-AUC of "
        f"**{best['pr_auc_mean']:.4f}**. The caveat above applies to that number too — "
        "it is near-perfect for the same reason.\n\n"
        "**The model is a component. The decision system around it is the deliverable:** "
        "an operating point chosen by how many payments a team can actually review, a "
        "threshold set by what a review costs and what a missed fraud costs, a served API "
        "that explains every decision it makes, a deployment that runs at no cost and "
        "rolls back on its own, and monitoring that will say when the model stops "
        "working.\n\n"
        "Those are the parts that transfer to a real portfolio. The accuracy figure does "
        "not."
    )

with st.expander("Running this yourself"):
    st.markdown(
        "Pages 1 and 2 need the scoring API. Point `API_BASE_URL` at a deployed instance, "
        "or run it locally with `uvicorn api.main:app --app-dir src`.\n\n"
        "Everything else on this dashboard renders from files committed to the repo "
        "(`data/processed/*.csv`) — nothing on this page was computed for this page load, "
        "which is what keeps it instant while the API is asleep."
    )
